from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, BarColumn, TextColumn, TimeElapsedColumn

from aniwa.models.profile import DatasetProfile


console = Console()


def render_console_report(profile: DatasetProfile, verbose: bool = False) -> None:
    """Render console report with optional progress indicators.
    
    Args:
        profile: DatasetProfile to render
        verbose: Enable detailed progress output during rendering
    """
    # Define report sections in order
    sections = [
        ("Metadata", _render_metadata if profile.metadata else None),
        ("Summary", _render_summary if profile.summary else None),
        ("Columns", _render_columns if profile.columns else None),
        ("Numeric Statistics", _render_numeric_stats if profile.columns else None),
        ("Data Quality", _render_quality if profile.quality else None),
        ("Insights", _render_insights if profile.insights is not None else None),
    ]
    
    # Filter out None sections
    sections = [(name, func) for name, func in sections if func is not None]
    
    # Header
    console.print()
    console.print(
        Panel.fit(
            "[bold cyan]Aniwa[/bold cyan]\n"
            "[white]Universal dataset profiling and intelligence[/white]\n"
            "[dim]See your data clearly.[/dim]",
            border_style="cyan",
            box=box.ROUNDED,
        )
    )
    
    # Render sections with optional progress
    if verbose and len(sections) > 1:
        with Progress(
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TimeElapsedColumn(),
            console=console,
            transient=True
        ) as progress:
            task = progress.add_task("Generating report sections...", total=len(sections))
            
            for section_name, render_func in sections:
                progress.update(task, description=f"  Rendering {section_name}")
                render_func(profile)
                progress.advance(task)
    else:
        for section_name, render_func in sections:
            if verbose:
                console.print(f"[dim] Rendering {section_name}...[/dim]")
            render_func(profile)
            if verbose:
                console.print(f"[dim]   {section_name} complete[/dim]")
    
    # Footer
    console.print("[dim]Generated by Aniwa - See your data clearly.[/dim]")
    console.print()


def _render_metadata(profile: DatasetProfile) -> None:
    if profile.metadata is None:
        return

    metadata = profile.metadata

    table = Table(
        title="Profiling Metadata",
        box=box.ROUNDED,
        border_style="cyan",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Field", style="bold")
    table.add_column("Value")

    _add_metadata_row(table, "Generated At", metadata.generated_at)
    _add_metadata_row(table, "Aniwa Version", metadata.aniwa_version)
    _add_metadata_row(table, "Python Version", metadata.python_version)
    _add_metadata_row(table, "Operating System", metadata.operating_system)
    _add_metadata_row(table, "Polars Version", metadata.polars_version)

    _add_metadata_row(table, "Dataset Path", metadata.dataset_path)
    _add_metadata_row(table, "File Type", metadata.dataset_file_type)
    _add_metadata_row(table, "Dataset Size", metadata.dataset_size)

    _add_metadata_row(table, "Profiling Mode", metadata.profiling_mode)
    _add_metadata_row(table, "Report Format", metadata.report_format)
    _add_metadata_row(table, "Report Template", metadata.report_template)

    _add_metadata_row(
        table,
        "Included Sections",
        ", ".join(metadata.included_sections)
        if metadata.included_sections
        else None,
    )

    _add_metadata_row(
        table,
        "Excluded Sections",
        ", ".join(metadata.excluded_sections)
        if metadata.excluded_sections
        else None,
    )

    _add_metadata_row(table, "Profiling Duration", metadata.profiling_duration)
    _add_metadata_row(table, "Command Used", metadata.command_used)

    console.print(table)


def _add_metadata_row(
    table: Table,
    field: str,
    value: str | None,
) -> None:
    if value is None:
        return

    table.add_row(field, value)


def _render_summary(profile: DatasetProfile) -> None:
    if profile.summary is None:
        return

    table = Table(
        title="Dataset Summary",
        box=box.ROUNDED,
        border_style="blue",
        show_header=True,
        header_style="bold blue",
    )

    table.add_column("Metric", style="bold")
    table.add_column("Value", justify="right")

    table.add_row("Rows", f"{profile.summary.rows:,}")
    table.add_row("Columns", f"{profile.summary.columns:,}")

    console.print(table)


def _render_quality(profile: DatasetProfile) -> None:
    if profile.quality is None:
        return

    table = Table(
        title="Data Quality",
        box=box.ROUNDED,
        border_style="red",
        show_header=True,
        header_style="bold red",
    )

    table.add_column("Metric", style="bold")
    table.add_column("Value", justify="right")

    table.add_row(
        "Duplicate Rows",
        f"{profile.quality.duplicate_rows:,}",
    )

    table.add_row(
        "Duplicate %",
        f"{profile.quality.duplicate_percent}%",
    )

    console.print(table)


def _render_columns(profile: DatasetProfile) -> None:
    if not profile.columns:
        return

    table = Table(
        title="Column Profile",
        box=box.ROUNDED,
        border_style="green",
        header_style="bold green",
    )

    table.add_column("Column", style="bold")
    table.add_column("Type")
    table.add_column("Nulls", justify="right")
    table.add_column("Null %", justify="right")
    table.add_column("Unique", justify="right")

    for col in profile.columns:
        null_style = _style_null_percent(col.null_percent)

        table.add_row(
            col.name,
            col.dtype,
            f"{col.null_count:,}",
            f"[{null_style}]{col.null_percent}%[/{null_style}]",
            f"{col.unique_count:,}",
        )

    console.print(table)


def _render_numeric_stats(profile: DatasetProfile) -> None:
    if not profile.columns:
        return

    numeric_columns = [
        col for col in profile.columns if col.numeric_stats
    ]

    if not numeric_columns:
        return

    table = Table(
        title="Numeric Statistics",
        box=box.ROUNDED,
        border_style="magenta",
        header_style="bold magenta",
    )

    table.add_column("Column", style="bold")
    table.add_column("Min", justify="right")
    table.add_column("Max", justify="right")
    table.add_column("Mean", justify="right")
    table.add_column("Median", justify="right")
    table.add_column("Std", justify="right")

    for col in numeric_columns:
        stats = col.numeric_stats

        if stats is None:
            continue

        table.add_row(
            col.name,
            _format_number(stats.min),
            _format_number(stats.max),
            _format_number(stats.mean),
            _format_number(stats.median),
            _format_number(stats.std),
        )

    console.print(table)


def _render_insights(profile: DatasetProfile) -> None:
    if profile.insights is None:
        return

    if len(profile.insights) == 0:
        console.print(
            Panel(
                "[green]No major issues detected.[/green]",
                title="Insights",
                border_style="green",
                box=box.ROUNDED,
            )
        )
        return

    # Group insights by level for better organization
    critical_insights = [i for i in profile.insights if i.level == "critical"]
    warning_insights = [i for i in profile.insights if i.level == "warning"]
    info_insights = [i for i in profile.insights if i.level == "info"]
    
    # Render critical insights first (most important)
    if critical_insights:
        table = Table(
            title="Critical Issues",
            box=box.ROUNDED,
            border_style="red",
            header_style="bold red",
        )
        table.add_column("Level")
        table.add_column("Message")
        
        for insight in critical_insights:
            table.add_row(
                _format_level(insight.level),
                insight.message,
            )
        console.print(table)
    
    # Then warnings
    if warning_insights:
        table = Table(
            title="Warnings",
            box=box.ROUNDED,
            border_style="yellow",
            header_style="bold yellow",
        )
        table.add_column("Level")
        table.add_column("Message")
        
        for insight in warning_insights:
            table.add_row(
                _format_level(insight.level),
                insight.message,
            )
        console.print(table)
    
    # Finally info messages
    if info_insights:
        table = Table(
            title="Information",
            box=box.ROUNDED,
            border_style="cyan",
            header_style="bold cyan",
        )
        table.add_column("Level")
        table.add_column("Message")
        
        for insight in info_insights:
            table.add_row(
                _format_level(insight.level),
                insight.message,
            )
        console.print(table)


def _style_null_percent(null_percent: float) -> str:
    if null_percent >= 75:
        return "bold red"

    if null_percent >= 40:
        return "yellow"

    return "green"


def _format_level(level: str) -> str:
    normalized = level.lower()

    if normalized == "critical":
        return "[bold red]CRITICAL[/bold red]"

    if normalized == "warning":
        return "[bold yellow]WARNING[/bold yellow]"

    if normalized == "info":
        return "[bold cyan]INFO[/bold cyan]"

    return level.upper()


def _format_number(value: float | None) -> str:
    if value is None:
        return "-"

    if float(value).is_integer():
        return f"{int(value):,}"

    return f"{value:,.4f}"