from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from aniwa.models.profile import DatasetProfile


console = Console()


def render_console_report(profile: DatasetProfile) -> None:
    console.print()
    console.print(
        Panel.fit(
            "[bold cyan]Aniwa[/bold cyan]\n"
            "[white]Universal dataset profiling and intelligence[/white]\n"
            "[dim]See your data clearly.[/dim]",
            border_style="cyan",
            box=box.ROUNDED,
        )
    )

    if profile.summary:
        _render_summary(profile)

    if profile.columns:
        _render_columns(profile)
        _render_numeric_stats(profile)

    if profile.insights is not None:
        _render_insights(profile)

    if profile.quality:
        _render_quality(profile)

    console.print("[dim]Generated by Aniwa — See your data clearly.[/dim]")
    console.print()


def _render_summary(profile: DatasetProfile) -> None:
    if profile.summary is None:
        return

    table = Table(
        title="Dataset Summary",
        box=box.ROUNDED,
        border_style="blue",
        show_header=True,
        header_style="bold blue",
    )

    table.add_column("Metric", style="bold")
    table.add_column("Value", justify="right")

    table.add_row("Rows", f"{profile.summary.rows:,}")
    table.add_row("Columns", f"{profile.summary.columns:,}")

    console.print(table)

def _render_quality(profile: DatasetProfile) -> None:
    if profile.quality is None:
        return

    table = Table(
        title="Data Quality",
        box=box.ROUNDED,
        border_style="red",
        show_header=True,
        header_style="bold red",
    )

    table.add_column("Metric", style="bold")
    table.add_column("Value", justify="right")

    table.add_row("Duplicate Rows", f"{profile.quality.duplicate_rows:,}")
    table.add_row("Duplicate %", f"{profile.quality.duplicate_percent}%")

    console.print(table)


def _render_columns(profile: DatasetProfile) -> None:
    table = Table(
        title="Column Profile",
        box=box.ROUNDED,
        border_style="green",
        header_style="bold green",
    )

    table.add_column("Column", style="bold")
    table.add_column("Type")
    table.add_column("Nulls", justify="right")
    table.add_column("Null %", justify="right")
    table.add_column("Unique", justify="right")

    for col in profile.columns:
        null_style = _style_null_percent(col.null_percent)

        table.add_row(
            col.name,
            col.dtype,
            f"{col.null_count:,}",
            f"[{null_style}]{col.null_percent}%[/{null_style}]",
            f"{col.unique_count:,}",
        )

    console.print(table)


def _render_numeric_stats(profile: DatasetProfile) -> None:
    numeric_columns = [col for col in profile.columns if col.numeric_stats]

    if not numeric_columns:
        return

    table = Table(
        title="Numeric Statistics",
        box=box.ROUNDED,
        border_style="magenta",
        header_style="bold magenta",
    )

    table.add_column("Column", style="bold")
    table.add_column("Min", justify="right")
    table.add_column("Max", justify="right")
    table.add_column("Mean", justify="right")
    table.add_column("Median", justify="right")
    table.add_column("Std", justify="right")

    for col in numeric_columns:
        stats = col.numeric_stats

        table.add_row(
            col.name,
            _format_number(stats.min),
            _format_number(stats.max),
            _format_number(stats.mean),
            _format_number(stats.median),
            _format_number(stats.std),
        )

    console.print(table)


def _render_insights(profile: DatasetProfile) -> None:
    if not profile.insights:
        console.print(
            Panel(
                "[green]No major issues detected.[/green]",
                title="Insights",
                border_style="green",
                box=box.ROUNDED,
            )
        )
        return

    table = Table(
        title="Insights",
        box=box.ROUNDED,
        border_style="yellow",
        header_style="bold yellow",
    )

    table.add_column("Level")
    table.add_column("Message")

    for insight in profile.insights:
        table.add_row(
            _format_level(insight.level),
            insight.message,
        )

    console.print(table)


def _style_null_percent(null_percent: float) -> str:
    if null_percent >= 75:
        return "bold red"

    if null_percent >= 40:
        return "yellow"

    return "green"


def _format_level(level: str) -> str:
    normalized = level.lower()

    if normalized == "critical":
        return "[bold red]CRITICAL[/bold red]"

    if normalized == "warning":
        return "[bold yellow]WARNING[/bold yellow]"

    if normalized == "info":
        return "[bold cyan]INFO[/bold cyan]"

    return level.upper()


def _format_number(value: float | None) -> str:
    if value is None:
        return "-"

    if value.is_integer():
        return f"{int(value):,}"

    return f"{value:,.4f}"