from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from aniwa.models.profile import DatasetProfile


def render_pdf_report(profile: DatasetProfile, output: str) -> None:
    output_path = Path(output)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=landscape(letter),
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Aniwa Dataset Profile", styles["Title"]))
    elements.append(Paragraph("Universal dataset profiling and intelligence report.", styles["BodyText"]))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Dataset Summary", styles["Heading2"]))

    summary_data = [
        ["Metric", "Value"],
        ["Rows", f"{profile.summary.rows:,}"],
        ["Columns", f"{profile.summary.columns:,}"],
        ["Duplicate Rows", f"{profile.quality.duplicate_rows:,}"],
        ["Duplicate %", f"{profile.quality.duplicate_percent}%"],
    ]

    summary_table = Table(summary_data, colWidths=[200, 200])
    _style_table(summary_table, header_color="#2563eb")
    elements.append(summary_table)
    elements.append(Spacer(1, 24))

    elements.append(Paragraph("Schema Profile", styles["Heading2"]))

    column_data = [["Column", "Type", "Nulls", "Null %", "Unique"]]

    for col in profile.columns:
        column_data.append(
            [
                col.name,
                col.dtype,
                f"{col.null_count:,}",
                f"{col.null_percent}%",
                f"{col.unique_count:,}",
            ]
        )

    column_table = Table(column_data, repeatRows=1)
    _style_table(column_table, header_color="#0f172a")
    elements.append(column_table)
    elements.append(Spacer(1, 24))

    numeric_columns = [col for col in profile.columns if col.numeric_stats]

    if numeric_columns:
        elements.append(Paragraph("Numeric Statistics", styles["Heading2"]))

        stats_data = [["Column", "Min", "Max", "Mean", "Median", "Std"]]

        for col in numeric_columns:
            stats = col.numeric_stats
            stats_data.append(
                [
                    col.name,
                    _format_value(stats.min),
                    _format_value(stats.max),
                    _format_value(stats.mean),
                    _format_value(stats.median),
                    _format_value(stats.std),
                ]
            )

        stats_table = Table(stats_data, repeatRows=1)
        _style_table(stats_table, header_color="#7c3aed")
        elements.append(stats_table)
        elements.append(Spacer(1, 24))

    if profile.insights:
        elements.append(Paragraph("Insights", styles["Heading2"]))

        insight_data = [["Level", "Message"]]

        for insight in profile.insights:
            insight_data.append([insight.level.upper(), insight.message])

        insight_table = Table(insight_data, colWidths=[120, 620], repeatRows=1)
        _style_table(insight_table, header_color="#ca8a04")
        elements.append(insight_table)

    elements.append(Spacer(1, 24))
    elements.append(Paragraph("Generated by Aniwa — See your data clearly.", styles["Italic"]))

    doc.build(elements)


def _style_table(table: Table, header_color: str) -> None:
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_color)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("TOPPADDING", (0, 0), (-1, 0), 10),
            ]
        )
    )


def _format_value(value: float | None) -> str:
    if value is None:
        return "-"

    if float(value).is_integer():
        return f"{int(value):,}"

    return f"{value:,.4f}"